/*! @file config.h
    @brief A configuration file that controls the options for the project and the target robot
    
    This file is automatically generated by CMake. Do NOT modify this file. Seriously, don't modify
    this file. If you really need to put something here, then you want to modify ./Make/config.in.

    @author Jason Kulk
 */
#ifndef CONFIG_H
#define CONFIG_H

// define the target robotic platform
#define TARGET_IS_NAOWEBOTS            //!< Preprocessor define for determine the target platform. Will be TARGET_IS_NAO, TARGET_IS_NAOWEBOTS, TARGET_IS_CYCLOID, etc

// define the os the code is being compiled on
#define MY_OS_Darwin              //!< Defintion that will be MY_OS_Windows, MY_OS_Darwin or MY_OS_Linux depending on your machines OS

// define the right MY_OS_IS_XXXXXXXX
#ifdef MY_OS_Windows
    #define MY_OS_IS_WINDOWS                    //!< This will be defined only this is being configured on a Windows machine
#else
    #undef MY_OS_IS_WINDOWS
#endif
#ifdef MY_OS_Darwin
    #define MY_OS_IS_DARWIN                     //!< This will be defined only when the build is configured on a OS-X machine
#else
    #undef MY_OS_IS_DARWIN
#endif
#ifdef MY_OS_Linux
    #define MY_OS_IS_LINUX                      //!< This will be defined only when the build is configured on a Linux machine
#else
    #undef MY_OS_IS_LINUX
#endif

// now define the os of the target robotic platform
#ifdef TARGET_IS_NAOWEBOTS                      // If we are targeting webots, then the target os is my os
    #ifdef MY_OS_IS_WINDOWS
        #define TARGET_OS_IS_WINDOWS            //!< This will be defined if the target's os is Windows
    #else
        #undef TARGET_OS_IS_WINDOWS
    #endif
    #ifdef MY_OS_IS_DARWIN
        #define TARGET_OS_IS_DARWIN             //!< This will be defined if the target's os is OS-X
    #else
        #undef TARGET_OS_IS_DARWIN
    #endif
    #ifdef MY_OS_IS_LINUX
        #define TARGET_OS_IS_LINUX              //!< This will be defined if the target's os is Linux
    #else
        #undef TARGET_OS_IS_LINUX
    #endif
#else                                           // If we are targeting an actual robot, then the target os is always linux
    #define TARGET_OS_IS_LINUX
#endif

// Thread priorities
#define THREAD_VISION_PRIORITY 0        //!< Controls the priority of the vision thread. I recommend that this be 0, however, if you are fealing adventurous set it to something non-zero and less than motion.
#define THREAD_MOTION_PRIORITY 40        //!< Controls the priority of the motion thread. This really needs to be non-zero, and less than the priority of any robot middleware

// Module Activation flags
// define variable to selectivly run vision
#define USE_VISION_OFF
#ifdef USE_VISION_ON
    #define USE_VISION                                          //!< this will be defined with the build is configured to include vision
#else
    #undef USE_VISION
#endif

// define variable to selectivly run localisation
#define USE_LOCALISATION_OFF
#ifdef USE_LOCALISATION_ON
    #define USE_LOCALISATION                                    //!< this will be defined when the build is configured to include localisation
#else
    #undef USE_LOCALISATION
#endif

// define variable to selectivly run behaviour
#define USE_BEHAVIOUR_ON
#ifdef USE_BEHAVIOUR_ON
    #define USE_BEHAVIOUR                                       //!< this will be defined when the build is configured to include behaviour
#else
    #undef USE_BEHAVIOUR
#endif

// define variable to selectivly run motion
#define USE_MOTION_ON
#ifdef USE_MOTION_ON
    #define USE_MOTION                                          //!< this will be defined when the build is configured to include motion
#else
    #undef USE_MOTION
#endif

#endif // !CONFIG_H

