/*! @file debugverbositynetwork.h
    @brief A configuration file that controls the debug options for the project
    
    This file is automatically generated by CMake. Do NOT modify this file. Seriously, don't modify
    this file. If you really need to put something here, then you want to modify ./Make/debug.in

    @author Jason Kulk
 */
#ifndef DEBUGVERBOSITYNETWORK_H
#define DEBUGVERBOSITYNETWORK_H

#define DEBUG_NETWORK_VERBOSITY 5              //!< Controls debug verbosity of the network module

#endif // !VERBOSITY_H

