/*! @file debugverbositynusensors.h
    @brief A configuration file that controls the debug options for the project
    
    This file is automatically generated by CMake. Do NOT modify this file. Seriously, don't modify
    this file. If you really need to put something here, then you want to modify ./Make/debug.in

    @author Jason Kulk
 */
#ifndef DEBUGVERBOSITYNUSENSORS_H
#define DEBUGVERBOSITYNUSENSORS_H

#define DEBUG_NUSENSORS_VERBOSITY 0          //!< Controls debug verbosity of the nusensors module

#endif // !VERBOSITY_H

