/*! @file debug.h
    @brief A configuration file that defines the method of text-based debuging
    
    This file is automatically generated by CMake. Do NOT modify this file. Seriously, don't modify
    this file. If you really need to put something here, then you want to modify ./Make/debug.in

    @author Jason Kulk
 */
#ifndef DEBUG_H
#define DEBUG_H

#include <iostream>
#include <fstream>

extern std::ofstream debug;
extern std::ofstream errorlog;

#endif // !DEBUG_H

