/*! @file debugverbositynusystem.h
    @brief A configuration file that controls the debug options for the project
    
    This file is automatically generated by CMake. Do NOT modify this file. Seriously, don't modify
    this file. If you really need to put something here, then you want to modify ./Make/debug.in

    @author Jason Kulk
 */
#ifndef DEBUGVERBOSITYNUSYSTEM_H
#define DEBUGVERBOSITYNUSYSTEM_H

#define DEBUG_NUSYSTEM_VERBOSITY 0            //!< Controls debug verbosity of the nusystem module

#endif // !VERBOSITY_H

