/*! @file debugverbosityvision.h
    @brief A configuration file that controls the debug options for the project
    
    This file is automatically generated by CMake. Do NOT modify this file. Seriously, don't modify
    this file. If you really need to put something here, then you want to modify ./Make/debug.in

    @author Jason Kulk
 */
#ifndef DEBUGVERBOSITYVISION_H
#define DEBUGVERBOSITYVISION_H

/*! 0 - off
*   1 - low     - typically only initialisation info
*   2 - medium  - minimal regularly changing info
*   3 - high    - full available debug info
*
*   Note: 2 and 3 make for increasing debug file size with runtime
*   Note: Do not implement level 1 to print more than once.
*/

#define DEBUG_VISION_VERBOSITY_ON
#ifdef DEBUG_VISION_VERBOSITY_ON
    #define VISION_SCAN_VERBOSITY       3
    #define VISION_BLACKBOARD_VERBOSITY 3
    #define VISION_CONTROLLER_VERBOSITY 3
    #define VISION_HORIZON_VERBOSITY    3
    #define VISION_WRAPPER_VERBOSITY    3
    #define VISION_LUT_VERBOSITY        3
    #define VISION_FILTER_VERBOSITY     3
    #define VISION_FIELDOBJECT_VERBOSITY 3
#else
    #define VISION_SCAN_VERBOSITY       0
    #define VISION_BLACKBOARD_VERBOSITY 0
    #define VISION_CONTROLLER_VERBOSITY 0
    #define VISION_HORIZON_VERBOSITY    0
    #define VISION_WRAPPER_VERBOSITY    0
    #define VISION_LUT_VERBOSITY        0
    #define VISION_FILTER_VERBOSITY     0
    #define VISION_FIELDOBJECT_VERBOSITY 0
#endif

#endif // !VERBOSITY_H

