/*! @file debugverbositynuplatform.h
    @brief A configuration file that controls the debug options for the project
    
    This file is automatically generated by CMake. Do NOT modify this file. Seriously, don't modify
    this file. If you really need to put something here, then you want to modify ./Make/debug.in

    @author Jason Kulk
 */
#ifndef DEBUGVERBOSITYNUPLATFORM_H 
#define DEBUGVERBOSITYNUPLATFORM_H 

#define DEBUG_NUPLATFORM_VERBOSITY 5        //!< Controls debug verbosity of the nuplatform module

#endif // !VERBOSITY_H

